DROP DATABASE IF EXISTS `471`;
CREATE DATABASE `471` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `471`;


DROP TABLE IF EXISTS USER;
CREATE TABLE USER
	(Username		VARCHAR(255)		NOT NULL,
	 SSN			INT					NOT NULL,
	 Password		VARCHAR(255)		NOT NULL,
	 Fname			VARCHAR(255)		NOT NULL,
	 Lname			VARCHAR(255)		NOT NULL,
	 Bdate			DATE				NOT NULL,
	 Sex			CHAR,
	PRIMARY KEY (Username, SSN)
);

DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF
	(Username		VARCHAR(255)		NOT NULL,
	 SSN			INT					NOT NULL,
	 Job			VARCHAR(255)		NOT NULL,
	PRIMARY KEY (Username, SSN),
	FOREIGN KEY (Username, SSN) REFERENCES USER(Username, SSN)
		ON DELETE CASCADE		ON UPDATE CASCADE
);

CREATE TABLE PASSENGER
	(P_ID			INT			NOT NULL,
	 Passport_Num	VARCHAR(255)		NOT NULL,
	PRIMARY KEY (P_ID, Passport_Num)
);


CREATE TABLE PURCHASER
	(Username		VARCHAR(255)		NOT NULL,
	 SSN			INT			NOT NULL,
	 P_ID			INT,
	PRIMARY KEY (Username, SSN),
	FOREIGN KEY (Username) REFERENCES USER(Username)
	ON DELETE CASCADE		ON UPDATE CASCADE,
	FOREIGN KEY (Username, SSN) REFERENCES USER(Username, SSN)
		ON DELETE CASCADE		ON UPDATE CASCADE,
	FOREIGN KEY (P_ID) REFERENCES PASSENGER(P_ID)
		ON DELETE SET NULL		ON UPDATE CASCADE
);
